SERVER:
  MAIN:
    name: zero-php-server
    listen: 0.0.0.0
    port: 7770
    model: PROCESS # BASE or PROCESS
    bootstrap: \App\Bootstrap
    setting: ~

FPM:
  MAIN:
    bootstrap: \App\Bootstrap

LOGGER:
  path: ~

MYSQL:
  core:
    host: 127.0.0.1
    port: 3306
    user: root
    password: test
    database: test

REDIS:
  cache:
    host: 127.0.0.1
    port: 6379
    auth: ~

GENERATE:
  doc:
    xxx: ~
  entity:
    db: core
  model:
    db: core
  table:
    db: core
